### PR TITLE
Add cdata example

### PR DESCRIPTION
**Pull request by rmalizia44**

### CODE REVIEW

**Review by jbampton — COMMENTED** [review]
The `pre-commit` check is failing.

You can read about how to setup `pre-commit` here:

https://github.com/mruby/mruby/blob/master/CONTRIBUTING.md#pre-commit

You can also run it with `Make` or `Rake`

**Comment by matz** [comment]
Can you squash the commits in this PR please?

**Comment by rmalizia44** [comment]
Done. I hope this helps who's trying to work with cdata in mruby.

**Comment by matz** [comment]
Thank you!

**Pull request merged**
