### PR TITLE
implement llround. some platform (ex: mingw32) doesn't have llround.

### PR DESCRIPTION
**Pull request by mattn**
if you want, I'll make block this part with `#ifdef _WIN32`.

### CODE REVIEW

**Comment by matz** [comment]
travis-ci test failed due to lack of `LONG_LONG_MAX` in `mrbgems/mruby-time/src/time.c`

**Comment by tsahara** [comment]
+1 for `#ifdef _WIN32` to reduce binary size.

**Comment by cremno** [comment]
But MinGW-w64 (which also targets 32-bit Windows) and VS 2013/2015 have `llround()`.

**Comment by mattn** [comment]
@cremno llround is macro which is possible to check with `#if defined(llround)`?

**Comment by mattn** [comment]
rebased. this should work.

**Comment by cremno** [comment]
@mattn: Does it have `round()`?

**Comment by mattn** [comment]
@cremno yes, but maybe not support long long.

**Comment by cremno** [comment]
Well, then let's use `round()`.

The body of a conforming definition of `llround()` can be as simple as `return (long long)round(x);` since [the range error is optional](http://port70.net/~nsz/c/c99/n1256.html#7.12.9.7p2).

**Comment by mattn** [comment]
@cremno please take a look.

**Pull request merged**
