### PR TITLE
Try Binding class

### PR DESCRIPTION
**Pull request by ksss**
I'm trying to implement CRuby's `Binding` class. 
`Binding#local_variables` is easy.
But I couldn't implement `Binding#eval` because it's too difficult.
It failed in this case.

```rb
class A
  class << self
    def b
      @a = 42
      b = 'local_variable'
      binding
    end
  end
end
p A.b.eval("[@a, b]")
# Expect: [42, "local_variable"]
# Actual(This branch): [42, []]
```

Does anyone have a good idea?

### CODE REVIEW

**Comment by take-cheeze** [comment]
Maybe recording the `struct RProc*` and `pc` of the previous stack frame could save the binding.

**Comment by dearblue** [comment]
@ksss, by saving the `REnv` object, the tests contained in your pull request will pass.
https://github.com/dearblue/mruby/tree/binding
This working branch is now the mruby HEAD (07224f8ed9aeb3b85bb0903adae04e8f3f60df5e).
Is it possible for you to continue the work you are planning?

**Comment by ksss** [comment]
@dearblue Hi.
Thank you for finding this PR.
But I've forgotten what this PR is all about and I have no motivation to continue with it.
I'm glad. If you will take over this project.

**Comment by dearblue** [comment]
I see.
Perhaps there are some parts that can not be implemented due to mruby restrictions, but I will issue a new pull request someday by adding methods that are lacking compared to CRuby.
Thank you for your reply.

**Comment by dearblue** [comment]
I have implemented anything but `Binding#irb` and created a pull request as #5362.
If you have any concerns, please ask them there.

**Comment by ksss** [comment]
@dearblue Great Job!!!! 🎉

**Pull request merged**
