### PR TITLE
add mrbc option `--remove-lv`

### PR DESCRIPTION
**Pull request by yurie**
* refactor: move `irep_remove_lv` from `mruby-bin-strip` gem to src/dump and rename to `mrb_irep_remove_lv`
* add: mrbc option `--remove-lv` to remove LVAR section

### CODE REVIEW

**Comment by matz** [comment]
The fundamental idea seems OK but is `src/dump.c` is the best place for `mrb_irep_remove_lv`?
It seems unnecessary for most of the cases. Maybe in `codegen.c`?

**Comment by yurie** [comment]
Updated.
Now declaration of the function is in `dump.h`. Should I move to `irep.h` or other file?

**Comment by matz** [comment]
`irep.h` seems better. Besides that, should we provide an option to remove all debug information altogether, not just lv?

**Comment by mimaki** [comment]
I agree to remove debug information.

2018-07-10 16:30 GMT+09:00 matz <notifications@github.com>:

**Comment by yurie** [comment]
moved to `irep.h`.

Summary of output debug information of `mrbc` with this patch:

 * (no option): `IREP`, `LVAR` sections
 * `-g` option: `IREP`, `DBG`, `LVAR` sections
 * `--remove-lv` option: `IREP` sections

**Pull request merged**
