### PR TITLE
include mruby.h before checking MRB_WITHOUT_FLOAT

### PR DESCRIPTION
**Pull request by takkaw**

### CODE REVIEW

**Comment by matz** [comment]
`MRB_WITHOUT_FLOAT` may be defined in `mrbconf.h` which is included from `mruby.h`.
This change requires `MRB_WITHOUT_FLOAT` to be defined in `CFLAGS`.

**Comment by takkaw** [comment]
> MRB_WITHOUT_FLOAT may be defined in mrbconf.h which is included from mruby.h.

Yes, I think so too.
Some files include mrbconf.h through including mruby.h to check MRB_WITHOUT_FLOAT.
But, including mruby.h is above checking MRB_WITHOUT_FLOAT in math.c and fmt_fp.c.


> This change requires MRB_WITHOUT_FLOAT to be defined in CFLAGS.

No. It's OK to be defined MRB_WITHOUT_FLOAT in mrbconf.h after this change.
Rather, MRB_WITHOUT_FLOAT is needed to be defined in CFLAGS without this change.

**Comment by matz** [comment]
I am sorry but probably I missed your point. Is it OK to define `MRB_WITHOUT_FLOAT` in `mrbconf.h` or not? It seems this PR prohibits `MRB_WITHOUT_FLOAT` in `mrbconf.h`.

**Comment by takkaw** [comment]
I intended that it's OK to define MRB_WITHOUT_FLOAT in mrbconf.h.
I'm sorry, I might have made a mistake so please let me check.

**Comment by dearblue** [comment]
When I proposed #4576, 'mrbconf.h' was missing completely.
Although it was late, I confirmed that if `MRB_WITHOUT_FLOAT` was defined in 'mrbconf.h', the expected error would occur.
Thanks to @takkaw!

**Pull request closed without merging**
