### PR TITLE
Simplify full-core.gembox

### PR DESCRIPTION
**Pull request by shuujii**
Dependencies order is auto detected.

### CODE REVIEW

**Comment by dearblue** [comment]
`mruby-print` and` mruby-sprintf` do not described their mutual dependencies.
Also, the order of filenames returned by the `Dir.glob` method is undefined.
Therefore, depending on the order, the `Kernel # printf` method will be unavailable (` mruby-sprintf` must be before `mruby-print`).

https://github.com/mruby/mruby/blob/45e8cb47ea0dab9a0cd22d2d78c728799f6a848c/mrbgems/mruby-print/mrblib/print.rb#L51-L54

As a means of solving this, I proposing it in the form of "weak dependency" (#4129).

**Comment by shuujii** [comment]
Sorry for breaking. How about a this solution? (https://github.com/shuujii/mruby/commit/778ea2a77a93accac59981b481a00633a22e63e3)

**Comment by matz** [comment]
I don't like dynamic dispatchin shuujii@778ea2a

**Comment by shuujii** [comment]
This PR can be re-merged because the dependency issue of `mruby-print` and `mruby-sprintf` was solved via 1d8456fe.

**Comment by dearblue** [comment]
@shuujii, How about making a new pull request?
You can reapply it by doing `git revert 37d795dec7b495d418dc2f9020cf980c158ba9ed`.

**Comment by shuujii** [comment]
Thank you for the comment. As I wrote in the comment above, I think that it can be merged as it is now, so I don't think it is necessary to make a new pull request.

**Comment by matz** [comment]
OK. I will reapply.

**Pull request merged**
