### PR TITLE
Merge mruby 2.1.1

### PR DESCRIPTION
**Pull request by mimaki**

### CODE REVIEW

**Comment by shuujii** [comment]
`mrbgems/mruby-io/test/mruby_io_test.c` should not be merged into master.

Also, if you're going to include a fix for #4981 into 2.1.1, I think it's better to include #4987.

**Comment by matz** [comment]
Could you explain why we should not include `mrbgems/mruby-io/test/mruby_io_test.c` into the master?

**Comment by shuujii** [comment]
Only the changes made in 2.1.1 branch should be merged from 2.1.1 branch to master branch.

The changes to `mrbgems/mruby-io/test/mruby_io_test.c` in 2.1.1 branch are part of the changes made in mater branch, which were later re-fixed, so the merging has resulted in a mix of old changes.

**Comment by matz** [comment]
Just for confirmation. Do you mean we should revert the changes done to `mruby_io_test.c` in 81d340e0421daf39a8208a0181d6a54e726db134?

**Comment by matz** [comment]
I understand. Thank you for the report @shuujii

**Pull request merged**
