### PR TITLE
Add `Docker` to build and run all `mruby` tests. Run `pre-commit` and generate `YARD` docs with Docker

### PR DESCRIPTION
**Pull request by jbampton**
This is a first pass at adding Docker for `mruby`. 
  
So far just installing and running `pre-commit` but in future both Make and/or Rake tasks could be added for further testing.  I can add more Docker docs in future too.

For ease of use there is Docker Desktop:

https://www.docker.com/products/docker-desktop/

Some images here:

Screen Shot 2023-04-03 at 1 25 30 am

Screen Shot 2023-04-03 at 1 25 52 am

Screen Shot 2023-04-03 at 1 23 36 am

### CODE REVIEW

**Comment by jbampton** [comment]
I have added the ability to generate the `YARD` docs with `docker-compose` now.
Probably can be improved in future.

Some new images:

Screen Shot 2023-04-03 at 5 38 21 am

Screen Shot 2023-04-03 at 5 38 35 am

Screen Shot 2023-04-03 at 5 39 25 am

Screen Shot 2023-04-03 at 5 40 01 am

**Comment by jbampton** [comment]
There is only one docker image that gets created now called `mruby-test`.  It is much better now being able to run custom commands.

Some images again:

Screen Shot 2023-04-03 at 11 15 21 am

Screen Shot 2023-04-03 at 11 24 24 am

Screen Shot 2023-04-03 at 11 26 23 am

Screen Shot 2023-04-03 at 11 24 44 am

**Comment by jbampton** [comment]
Hey @matz this is ready for review now.

Running the default `docker-compose` command will now build and run all `mruby` tests.

You can run `pre-commit` and generate the YARD docs too.

An image of the successful  test run:

Screen Shot 2023-04-03 at 3 31 45 pm

**Comment by matz** [comment]
Could you resolve the conflict caused by 076520c?
I am not sure the benefit of running pre-commit and tests in docker environment. Could you explain a bit more?

**Comment by jbampton** [comment]
The main benefits are that you won't need to install the prerequisites to compile mruby with Rake.

Also all the RubyGems are installed to build the YARD docs so you don't need to install those either.

And the pre-commit hooks are installed in Docker too so you don't need to install pre-commit or a package manager from which you get pre-commit.

Some people have trouble installing software and this is more prevalent on Windows.

**Pull request merged**
