### PR TITLE
Revert "Create presym files for each build target" (58ba883e)

### PR DESCRIPTION
**Pull request by shuujii**
Due to the above changes, it may not work with the existing build
configurations in cross-compilation (even if we can build without presym),
therefore revert it once (ref https://github.com/mruby/mruby/pull/5202#issuecomment-735412643). Sorry for the lack of consideration.

### CODE REVIEW

**Comment by matz** [comment]
It's OK we can make it safe before the release. Thank you!

**Comment by zzak** [comment]
@shuujii Hello! Thank you for your work on build system recently!!

I'm trying to build against your branch including the `presym` changes to compile `mruby-compiler` gem but I get this error:

```
In file included from src/mruby/include/mruby.h:96,
                 from src/mruby/mrbgems/mruby-compiler/core/codegen.c:11:
src/mruby/mrbgems/mruby-compiler/core/codegen.c: In function ‘codegen’:
src/mruby/include/mruby/presym.h:46:25: error: ‘MRB_SYM__compile’ undeclared (first use in this function); did you mean ‘MRB_SYM__coding’?
 #define MRB_SYM(name)   MRB_SYM__##name    /* Word characters */
                         ^~~~~~~~~
src/mruby/mrbgems/mruby-compiler/core/codegen.c:2719:24: note: in expansion of macro ‘MRB_SYM’
       sym = new_sym(s, MRB_SYM(compile));
                        ^~~~~~~
src/mruby/include/mruby/presym.h:46:25: note: each undeclared identifier is reported only once for each function it appears in
 #define MRB_SYM(name)   MRB_SYM__##name    /* Word characters */
                         ^~~~~~~~~
src/mruby/mrbgems/mruby-compiler/core/codegen.c:2719:24: note: in expansion of macro ‘MRB_SYM’
       sym = new_sym(s, MRB_SYM(compile));
```

Here is the command I used:

```
cc -D"MRB_NO_GEMS" -I"src/mruby/include" -I"src/mruby/build/host/include" -o "src/mruby/build/host/mrbgems/mruby-compiler/core/codegen.o" -c "src/mruby/mrbgems/mruby-compiler/core/codegen.c"
```

Inside "src/mruby/build/host/include" is just "mruby/presym.inc", if it's helpful I can paste the full contents of this file.

**Comment by shuujii** [comment]
Hi @zzak.

You've tried 58ba883e (or https://github.com/shuujii/mruby/tree/create-presym-files-for-each-build-target), right?

There were some problems with that, so I've fixed them afterwards. Could you try it with the version just before this revert commit (98d5aa8d)? If it still reproduces, could you please show me the build configuration?

BTW, it is strange that `MRB_NO_GEMS` is defined even though` mruby-compiler` gem is used.

**Comment by zzak** [comment]
@shuujii Thanks for your reply.

I've tried both revisions, with "build/host/include/presym.inc" version and with "build/presym.inc" version.

Now that you mentioned about `MRB_NO_GEMS` (I was trying to compile `libmruby_core.a` by hand), and the fact that my `presym.inc` file seems much shorter than the one generated by mruby HEAD -- I think something in my configuration is missing or incorrect.

I'd love to share this with you and get your feedback.

Would it be possible to email you?

My address is zzakscott <at> gmail

**Comment by shuujii** [comment]
@zzak If you were manually compiling to create `libmruby_core.a`, #5212 no longer requires you to do so.

**Pull request merged**
