### PR TITLE
GitHub labeler: label more files

### PR DESCRIPTION
**Pull request by jbampton**
These are some of the config files for the linters/tests that run

### CODE REVIEW

**Comment by jbampton** [comment]
See in refs #6204 that the pull request was not labeled.

Best to have labels for all files / folders.

**Comment by dearblue** [comment]
I think it's a bit different to belong to the `build` label.

:thinking: Since I think the number is small and not a noteworthy classification, I propose `miscellaneous` and cast my vote.
Other label names I can think of are `edit`, `coding`, and `utility`.
If there is another preferred proposal, I may vote for that one.

**Comment by jbampton** [comment]
Thanks @dearblue I went with `miscellaneous` for the new label

**Comment by jbampton** [comment]
Hey @matz 

I forgot to mention that we need to add the new label for `miscellaneous` on the repo labels page here:

https://github.com/mruby/mruby/labels

Thanks

**Comment by matz** [comment]
Done.

**Pull request merged**
