### PR TITLE
ossfuzz: Add simple mruby compile test harness

### PR DESCRIPTION
**Pull request by bshastry**
I took the initiative to make a proposal to continuously fuzz mruby compiler with oss-fuzz. The plan is the following:

- To kick things off, we add a simple libFuzzer style test harness called `ossfuzz/mruby_fuzzer.c` that
  - Takes input from the fuzzer
  - Creates a C string from this input and feeds it to the mruby compiler
- There is also some boilerplate code for (de)initialization
- Additionally, there is a directory called `ossfuzz/config`
  - `mruby.dict` is a fuzzing dictionary courtesy @bovi that is meant to assist the fuzzer discover interesting program paths
  - `mruby_fuzzer.options` is an oss-fuzz specific fuzzing configuration file

If this PR is approved, I will make a namesake PR to oss-fuzz that includes a build script for creating the fuzzing binary from this test harness. The rest (fuzz automation, bug reporting etc.) is taken care of by oss-fuzz itself.

I would also need a gmail address of the primary mruby contact point so that you can login to the fuzzer infrastructure offered by Google and view bug reports and the like. Optionally, you could add other contact points but for the additional persons, a gmail address is not necessary iirc.

Feedback welcome.

### CODE REVIEW

**Comment by bshastry** [comment]
Hello everyone,

Any updates on this PR? Feedback appreciated.

Thank you.

**Comment by bshastry** [comment]
Hello,

Quick ping to get feedback on this PR: Would you be interested in continuously fuzzing the mruby interpreter? If not feel free to close this PR.

**Comment by matz** [comment]
Sorry for being late. I still don't fully understand how ossfuzz works.
But it seems harmless to existing code.

**Comment by matz** [comment]
Checking by oss-fuzz has started. I have received several issues. But I have to sign in to the system using my google account but my registered address is not. @bshastry Is there any way to resolve this?

**Comment by bshastry** [comment]
Hello @matz. I can add your Gmail address. Could you please send it to me.

**Pull request merged**
