### PR TITLE
Include an header in same dir

### PR DESCRIPTION
**Pull request by MatteoRagni**
Solves including error raised during cross compilations

### CODE REVIEW

**Comment by mattn** [comment]
related issue #656

**Comment by MatteoRagni** [comment]
I'm not using xcode. The syntax error is raised for other embedded
platforms linux based.

Il giorno 02:34 ven 27/feb/2015 mattn <notifications@github.com> ha scritto:

**Comment by matz** [comment]
Could you show us your error messages?

**Comment by MatteoRagni** [comment]
Not now. It is an explicit not found

Il giorno 09:17 ven 27/feb/2015 matz <notifications@github.com> ha scritto:

**Comment by zzak** [comment]
I think this is a duplicate of #2603

**Comment by matz** [comment]
I think this resolved by 5c405de (#3032).

**Pull request closed without merging**
