### PR TITLE
`dreamcast_shelf` build config: complete overhaul.

### PR DESCRIPTION
**Pull request by sizious**
This configuration is used to support the **Sega Dreamcast** system. 
mruby is now officially supported as a KallistiOS Port in `kos-ports`.
See: https://dreamcast.wiki/Using_Ruby_for_Sega_Dreamcast_development

### CODE REVIEW

**Comment by sizious** [comment]
Sorry but I don't know where the problem the Linter is complaining about comes from.

**Comment by sizious** [comment]
Conversion to Draft mode to understand why the Linter isn't happy

**Comment by dearblue** [comment]
The error points to something unrelated to this PR, so it should be fine as it is.

**Comment by sizious** [comment]
Replaced by: https://github.com/mruby/mruby/pull/6130

**Pull request closed without merging**
