### PR TITLE
Remove implementation of `Symbol#===`

### PR DESCRIPTION
**Pull request by shuujii**
For reducing program size.

### CODE REVIEW

**Comment by take-cheeze** [comment]
This shouldn't be merged.
`Symbol#===` should be moved to `mruby-symbol-ext` gem.
Though this may change behavior of `case ～ when ～ end` and will broke some code.

**Comment by take-cheeze** [comment]
See: https://wandbox.org/permlink/haMjLZxsE4drNBxV

**Comment by shuujii** [comment]
Sorry, I don't understand what is the problem. Example above seems to produce the same result before and after this change.

**Comment by matz** [comment]
@take-cheeze probably you have misunderstood the behavior of `undef`. The `undef` operator makes the specified method uncallable (thus an error in wandbox), whereas this patch removes the definition from `Symbol` class (and makes the overridden `Kernel#===` appeared).

**Comment by take-cheeze** [comment]
Ah, sorry seems to fallback to `Kernel#===` .

**Comment by take-cheeze** [comment]
And CRuby uses `rb_obj_equal` too.
https://github.com/ruby/ruby/blob/46968fab0a0cec4a3e6e37f30b13d20998ba5e7a/string.c#L10493
Specializing like `mrb_type(rhs) == MRB_TT_SYMBOL && mrb_symbol(self) == mrb_symbol(rhs)` seems to be better implementation.

**Comment by take-cheeze** [comment]
Though it still makes incompatibility with CRuby: https://wandbox.org/permlink/cCS7wIV2sfqUjoyv

**Comment by matz** [comment]
This is the undefined behavior in ISO, so the difference is OK, I think (and no one removes the important `===` from `Kernel` module in realistic applications).

**Pull request merged**
