### PR TITLE
fix build on vs2013-vs2015

### PR DESCRIPTION
**Pull request by mattn**

### CODE REVIEW

**Comment by mattn** [comment]
Hmm, still not. I have no idea. :(

**Comment by mattn** [comment]
I figure out why appveyor fail.

```c
#  define const
```
(in src/string.c)

This is wrong. This break signature for mrb_float_read.

**Comment by mattn** [comment]
@matz Is this required?

```c
#ifndef __STDC__
# ifdef __GNUC__
#  define const __const__
# else
#  define const
# endif
#endif
```

**Comment by matz** [comment]
It was copied from ruby1.8/missing. Probably for compatibility with old compilers.

**Pull request merged**
