### PR TITLE
More Docs

### PR DESCRIPTION
**Pull request by sagmor**
Now docs are covering most of the sources including mani fixes to parse some special cases and include all mrbgems in the generated docs.

### CODE REVIEW

**Comment by matz** [comment]
I will merge this soon.  But I am not fully satisfied with enormous `@mrbgem` tags.
Is there any other way?

**Comment by sagmor** [comment]
I could try to figure out a way.
I could use the fact that those files live inside `mrbgems` directory to tag them "automagically" :sparkles: 

What if:
I revert 5cdcce8dbddd94ecb9503a0a1d47370c4ef97177 and give it more thought time to skip the abundant `@mrbgem` tags?

**Comment by matz** [comment]
@sagmor that's better. I will merge this after your revert.

**Comment by sagmor** [comment]
@matz :heavy_check_mark:

**Pull request merged**
