### PR TITLE
Replace `MRB_NO_DIRECT_THREADING` with `MRB_USE_VM_SWITCH_DISPATCH`

### PR DESCRIPTION
**Pull request by dearblue**
The correct technique now is "Token Threading".
However, the new name was chosen because it was felt that if a different technique was added in the future, there would be no need to replace it.

### CODE REVIEW

**Comment by matz** [comment]
I am not sure how proposed wording is better. Could you explain?

**Comment by dearblue** [comment]
:black_cat: My only source of information is https://ja.wikipedia.org/wiki/スレッデッドコード, which may be suspect.

  - The current implementation is based on "Token threading".
  - "Direct threading" is not "Token threading".
  - "Token threading" is not "Direct threading".
  - "Threaded code" includes "Token threading", "Direct threading", "Huffman threading" and etc..

**Comment by dearblue** [comment]
I fixed the conflicts and rebased.

**Comment by matz** [comment]
I understand the wording (and I am sure it's valid, since Prof. Ertl mentioned). But since we see “switch threading” in the [reference](http://www.complang.tuwien.ac.at/forth/threaded-code.html), so if used precisely, the term threaded code itself is meaningless. Let me think about it for a while.

**Comment by dearblue** [comment]
Oh, "Switch threading".
Hmmm, I'll leave this PR open for now, but switch to draft.

**Comment by dearblue** [comment]
How about `MRB_USE_SWITCH_THREADING`?
Or is `MRB_USE_VM_SWITCH_DISPATCH` more understandable?

**Comment by matz** [comment]
I prefer the term "switch dispatch" to "switch threading", for not using direct goto.

**Comment by dearblue** [comment]
Thanks for your comment.
Replaced with `MRB_USE_VM_SWITCH_DISPATCH`.

And `DIRECT_THREADED` has been merged into `MRB_USE_VM_SWITCH_DISPATCH`.
So, please note that `#ifdef` and `#ifndef` have been replaced by the reverse.

**Pull request merged**
