### PR TITLE
Build and test on macOS 13

### PR DESCRIPTION
**Pull request by jbampton**
https://github.com/actions/runner-images#available-images

### CODE REVIEW

**Comment by matz** [comment]
I don't know the reason, but `bintest` failed on macos 13.

**Comment by matz** [comment]
Still fails.

**Comment by jbampton** [comment]
Yes it is failing still.  I am not sure why.

**Comment by jbampton** [comment]
Hey @matz the macOS 13 build is now passing :+1: 

Ready for review

**Comment by matz** [comment]
OK. I have received a mail from GitHub that said they would remove macOS 12 support soon. Could you make a patch (or should I)?

**Pull request merged**
