### PR TITLE
Extract mrbtest to binary gem

### PR DESCRIPTION
**Pull request by zzak**
This will allow us to create specific target `MRuby::Build`s for our tests.

Previously the test library, and optionally the binary, were compiled for every build.

### CODE REVIEW

**Comment by matz** [comment]
I like the concept of the PR, but Tavis failed.

**Comment by zzak** [comment]
@matz Yeah I can reproduce the travis failure locally with `MRUBY_CONFIG=travis_config.rb ./minirake all test` but I'm not sure why yet.

**Comment by zzak** [comment]
So I've narrowed it down to when `conf.gembox "full-core"` is used instead of `"default"`. But I'm not quite sure why yet.. here's a stacktrace:

```
NoMethodError: undefined method `each' for nil:NilClass
/Users/zscott/code/mruby/tasks/mrbgem_spec.rake:306:in `block in generate_gem_table'
/Users/zscott/code/mruby/tasks/mrbgem_spec.rake:286:in `each'
/Users/zscott/code/mruby/tasks/mrbgem_spec.rake:286:in `each'
/Users/zscott/code/mruby/tasks/mrbgem_spec.rake:305:in `generate_gem_table'
/Users/zscott/code/mruby/mrbgems/mruby-test/mrbgem.rake:35:in `block in <top (required)>'
/Users/zscott/code/mruby/tasks/mrbgem_spec.rake:80:in `instance_eval'
/Users/zscott/code/mruby/tasks/mrbgem_spec.rake:80:in `setup'
/Users/zscott/code/mruby/tasks/ruby_ext.rake:41:in `block in to_proc'
/Users/zscott/code/mruby/tasks/mrbgem_spec.rake:286:in `each'
/Users/zscott/code/mruby/tasks/mrbgem_spec.rake:286:in `each'
/Users/zscott/code/mruby/tasks/mrbgems.rake:4:in `block in <top (required)>'
/Users/zscott/code/mruby/tasks/mruby_build.rake:13:in `instance_eval'
/Users/zscott/code/mruby/tasks/mruby_build.rake:13:in `block in each_target'
/Users/zscott/code/mruby/tasks/mruby_build.rake:12:in `each'
/Users/zscott/code/mruby/tasks/mruby_build.rake:12:in `each_target'
/Users/zscott/code/mruby/tasks/mrbgems.rake:1:in `<top (required)>'
/Users/zscott/code/mruby/Rakefile:26:in `load'
/Users/zscott/code/mruby/Rakefile:26:in `<top (required)>'
```

**Comment by zzak** [comment]
The build is green as of 87564dc! <3

**Pull request merged**
