### PR TITLE
Add missing MRB_API

### PR DESCRIPTION
**Pull request by kou**
MRB_API is used implementation in load.c:

    MRB_API mrb_irep*
    mrb_read_irep_file(mrb_state *mrb, FILE* fp)

### CODE REVIEW

**Comment by matz** [comment]
I considered mrb_read_irep_file() to be an internal function. Do you have any use-case of the function?

**Comment by kou** [comment]
I don't have any use-case. I just want to build (link) error.
Could you remove `MRB_API` in load.c?

**Comment by kou** [comment]
I just want to "fix" build (link) error...

**Comment by matz** [comment]
I see inconsistency.  Will fix.

**Comment by kou** [comment]
Thanks. But I found more same cases. I created a new pull request as #3216.

**Pull request closed without merging**
