### PR TITLE
feat: add pre-commit framework

### PR DESCRIPTION
**Pull request by jbampton**
Official -> "Git hook scripts are useful for identifying simple issues before submission to code review. We run our hooks on every commit to automatically point out issues in code such as missing semicolons, trailing whitespace, and debug statements. By pointing these issues out before code review, this allows a code reviewer to focus on the architecture of a change while not wasting time with trivial style nitpicks." 

https://pre-commit.com/

Using a pre-commit framework speeds up development as a lot of tests can be run on the local machine giving instant feedback.  So we don't have to wait for the CI / GitHub actions to run to get feedback.  The pre-commit automatically fixes some of the issues when you do `git commit` and if there are any issues the tests are marked as `red` failed.  Then you will need to commit again so that all the tests pass green.

There are many more pre-commit checks listed here -> https://pre-commit.com/hooks.html

Lets get this PR merged and then I will look at adding more pre-commit tests 👍 

The next image shows the final pre-commit run -> running for this PR on my local machine:

Screen Shot 2021-03-01 at 10 06 55 am

### CODE REVIEW

**Comment by dearblue** [comment]
I'm a little late, but here's a report on the results of trying out pre-commit.

In my machine, the related installation of pre-commit fails, so I can't do `git commit` anymore.
That's why I did a "pre-commit uninstall". 

```console
% uname -v
FreeBSD 12.2-RELEASE-p4 GENERIC

% sudo pkg install devel/py-pre-commit
...SNIP...

% pre-commit install
pre-commit installed at .git/hooks/pre-commit

% touch test-precommit
% git add test-precommit
% git ci -m test
[WARNING] Unstaged files detected.
[INFO] Stashing unstaged files to /usr/home/dearblue/.cache/pre-commit/patch1615701609.
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Initializing environment for https://github.com/igorshubovych/markdownlint-cli.
[INFO] Initializing environment for https://github.com/adrienverge/yamllint.
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/igorshubovych/markdownlint-cli.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Restored changes from /usr/home/dearblue/.cache/pre-commit/patch1615701609.
An unexpected error has occurred: CalledProcessError: command: ('/usr/local/bin/python3.7', '-mnodeenv', '--prebuilt', '--clean-src', '/usr/home/dearblue/.cache/pre-commit/repoq916t6ot/node_env-default')
return code: 1
expected return code: 0
stdout: (none)
stderr:
     * Install prebuilt node (15.11.0) .
    Traceback (most recent call last):
      File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
        "__main__", mod_spec)
      File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "/usr/local/lib/python3.7/site-packages/nodeenv.py", line 1471, in <module>
        main()
      File "/usr/local/lib/python3.7/site-packages/nodeenv.py", line 1065, in main
        create_environment(env_dir, opt)
      File "/usr/local/lib/python3.7/site-packages/nodeenv.py", line 951, in create_environment
        install_node(env_dir, src_dir, opt)
      File "/usr/local/lib/python3.7/site-packages/nodeenv.py", line 716, in install_node
        install_node_wrapped(env_dir, src_dir, opt)
      File "/usr/local/lib/python3.7/site-packages/nodeenv.py", line 738, in install_node_wrapped
        download_node_src(node_url, src_dir, opt)
      File "/usr/local/lib/python3.7/site-packages/nodeenv.py", line 565, in download_node_src
        dl_contents = io.BytesIO(urlopen(node_url).read())
      File "/usr/local/lib/python3.7/site-packages/nodeenv.py", line 601, in urlopen
        return urllib2.urlopen(req)
      File "/usr/local/lib/python3.7/urllib/request.py", line 222, in urlopen
        return opener.open(url, data, timeout)
      File "/usr/local/lib/python3.7/urllib/request.py", line 531, in open
        response = meth(req, response)
      File "/usr/local/lib/python3.7/urllib/request.py", line 641, in http_response
        'http', request, response, code, msg, hdrs)
      File "/usr/local/lib/python3.7/urllib/request.py", line 569, in error
        return self._call_chain(*args)
      File "/usr/local/lib/python3.7/urllib/request.py", line 503, in _call_chain
        result = func(*args)
      File "/usr/local/lib/python3.7/urllib/request.py", line 649, in http_error_default
        raise HTTPError(req.full_url, code, msg, hdrs, fp)
    urllib.error.HTTPError: HTTP Error 404: Not Found

Check the log at /usr/home/dearblue/.cache/pre-commit/pre-commit.log
```

**Comment by jbampton** [comment]
Seems the error message mentions missing Node:

Screen Shot 2021-03-14 at 9 12 35 pm

**Comment by dearblue** [comment]
Hmmm, `node` is already installed from a package by FreeBSD, and `markdownlint` works fine with `sudo npm install -g markdownlint-cli`.

```console
% node --version
v15.9.0
% nodeenv --version
1.5.0
```

Maybe the `node` version is old, but building from raw source code that I don't understand is very difficult for me...

**Comment by jbampton** [comment]
Can you install `pre-commit` in one of the standard ways ?   

https://pre-commit.com/

Screen Shot 2021-03-14 at 10 55 26 pm

I am running `pre-commit` version 2.11.1

Screen Shot 2021-03-14 at 10 56 58 pm

Under `mruby` folder I have:

Screen Shot 2021-03-14 at 9 11 57 pm

**Comment by dearblue** [comment]
Thanks! The `pre-commit` is works!
As it turns out, the FreeBSD package that provided it was out of date.

```console
% sudo pkg delete py37-pre-commit
...SNIP...
[1/1] Deleting files for py37-pre-commit-1.21.0: 100%

% sudo pip install pre-commit
...SNIP...
Installing collected packages: pre-commit
Successfully installed pre-commit-2.11.1
```

However, it seems that unmanaged files are also covered by `yamllint`, which is a problem.

```console
% pre-commit run -v --all-files
identity.................................................................Passed
- hook id: identity
- duration: 0.17s

...SNIP...

Check hooks apply to the repository......................................Passed
- hook id: check-hooks-apply
- duration: 0.41s
Check for added large files..............................................Passed
- hook id: check-added-large-files
- duration: 0.36s
Check for case conflicts.................................................Passed
- hook id: check-case-conflict
- duration: 0.23s
Check for merge conflicts................................................Passed
- hook id: check-merge-conflict
- duration: 0.16s
Check Yaml...............................................................Passed
- hook id: check-yaml
- duration: 0.44s
Fix End of Files.........................................................Passed
- hook id: end-of-file-fixer
- duration: 0.17s
fix UTF-8 byte order marker..............................................Passed
- hook id: fix-byte-order-marker
- duration: 0.17s
Mixed line ending........................................................Passed
- hook id: mixed-line-ending
- duration: 0.23s
Trim Trailing Whitespace.................................................Passed
- hook id: trailing-whitespace
- duration: 0.24s
Run markdownlint.........................................................Passed
- hook id: markdownlint
- duration: 0.68s
Check YAML files with yamllint...........................................Failed
- hook id: yamllint
- duration: 14.7s
- exit code: 1

./build_config/concept.yaml
  4:14      warning  too few spaces before comment  (comments)
  9:10      warning  too few spaces before comment  (comments)
  10:8      warning  too few spaces before comment  (comments)
  13:3      error    wrong indentation: expected 4 but found 2  (indentation)
  16:1      error    wrong indentation: expected 2 but found 0  (indentation)
  18:1      error    wrong indentation: expected 2 but found 0  (indentation)
  21:5      error    wrong indentation: expected 6 but found 4  (indentation)
  22:9      warning  too few spaces before comment  (comments)

./build_config/concept.yaml
  4:14      warning  too few spaces before comment  (comments)
  9:10      warning  too few spaces before comment  (comments)
  10:8      warning  too few spaces before comment  (comments)
  13:3      error    wrong indentation: expected 4 but found 2  (indentation)
  16:1      error    wrong indentation: expected 2 but found 0  (indentation)
  18:1      error    wrong indentation: expected 2 but found 0  (indentation)
  21:5      error    wrong indentation: expected 6 but found 4  (indentation)
  22:9      warning  too few spaces before comment  (comments)

./build_config/concept.yaml
  4:14      warning  too few spaces before comment  (comments)
  9:10      warning  too few spaces before comment  (comments)
  10:8      warning  too few spaces before comment  (comments)
  13:3      error    wrong indentation: expected 4 but found 2  (indentation)
  16:1      error    wrong indentation: expected 2 but found 0  (indentation)
  18:1      error    wrong indentation: expected 2 but found 0  (indentation)
  21:5      error    wrong indentation: expected 6 but found 4  (indentation)
  22:9      warning  too few spaces before comment  (comments)
```

I have therefore changed the `.pre-commit-config.yaml` file, but I am not sure if it is correct.

```diff
diff --git a/.pre-commit-config.yaml b/.pre-commit-config.yaml
index 0a9da963f..6d48f4125 100644
--- a/.pre-commit-config.yaml
+++ b/.pre-commit-config.yaml
@@ -35,5 +35,5 @@ repos:
     hooks:
       - id: yamllint
         name: Check YAML files with yamllint
-        entry: yamllint --strict .
+        entry: yamllint --strict
         types: [yaml]
```

**Comment by jbampton** [comment]
We can ignore files or directories from `yamllint`:

https://yamllint.readthedocs.io/en/stable/configuration.html#ignoring-paths

Screen Shot 2021-03-15 at 12 16 21 am

**Comment by dearblue** [comment]
I don't think it's realistic to add every single file/directory that is not managed by `git`.

I tried looking at the `pre-commit` documentation a bit, and it seems that the necessary arguments are passed each time the command is invoked.

  - The configuration file I tried:
    ```diff
    diff --git a/.pre-commit-config.yaml b/.pre-commit-config.yaml
    index 0a9da963f..d7943a2bc 100644
    --- a/.pre-commit-config.yaml
    +++ b/.pre-commit-config.yaml
    @@ -9,6 +9,12 @@ repos:
         hooks:
           - id: identity
           - id: check-hooks-apply
    +  - repo: local
    +    hooks:
    +    - id: checkargv
    +      name: test argv by ruby
    +      entry: ruby30 -e 'p ARGV; exit 1'
    +      language: system
       - repo: https://github.com/pre-commit/pre-commit-hooks
         rev: v3.4.0
         hooks:
    @@ -35,5 +41,5 @@ repos:
         hooks:
           - id: yamllint
             name: Check YAML files with yamllint
    -        entry: yamllint --strict .
    +        entry: yamllint --strict
             types: [yaml]

    ```

    Now, when I run `pre-commit run --all-files`, I see that ruby30 was called several times.
    I can also confirm that this change also causes errors in `.pre-commit-config.yaml`.

Currently it is run as `yamlint --strict .` but I don't think it is necessary to specify the directory.

Is there a different reason that I am not aware of?

**Pull request merged**
