### PR TITLE
Change second argument to `%l` of `mrb_vformat()` to `size_t` from `mrb_int`

### PR DESCRIPTION
**Pull request by shuujii**
- `size_t` is more commonly used.
- `len` argument of `mrb_str_new()` is `size_t`.

NOTE:

The test for `%l` is temporarily disabled because adding a new type to
`mrbgems/mruby-test/vformat.c` causes an error (memory error?) on Visual
Studio 2017 in AppVeyor.

### CODE REVIEW

**Comment by matz** [comment]
Once it works on Appveyor (or @shuujii says go), I will merge this.

**Comment by shuujii** [comment]
I will fix build in AppVeyor later, so could you please merge it once?

**Comment by shuujii** [comment]
Thank you for merging.

**Comment by matz** [comment]
I could implement `%l` test in a different way.

**Pull request merged**
