### PR TITLE
Gracefully handle clashing git checkout names (plus load_gems.rb refactor)

### PR DESCRIPTION
**Pull request by suetanvil**
This is a fix for https://github.com/mruby/mruby/issues/5574 .

The problem is that when retrieving gem dependencies from git repositories, if two or more repositories have the same basename, the retrieval system will get confused and treat it as one or another, depending on declaration order.  This is also the case when using different branches or commits from the same repository.

This change fixes this as follows:

1. It is now an error to attempt to clone more than one gem to the same directory **unless** they are identical (same url, branch, and commit ID).
2. It is possible to declare the first import of a gem as being "canonical". This will cause the system to ignore duplicate imports with a message.

In addition, I have refactored `load_gems.rb` to improve maintainability.  Specifically, the function `load_special_path_gem` has been turned into a class with the functionality spread across multiple descriptively-named private methods.

### CODE REVIEW

**Comment by matz** [comment]
Could you clean up the pull-request?
- cancelling rebuild.sh
- separate unrelated trailing space removal of README.md in mruby-errno

**Comment by suetanvil** [comment]
I'll try to do that within the next to or 3 days.

**Comment by suetanvil** [comment]
The requested changes have been made. Please let me know if you need anything else.

**Comment by matz** [comment]
Merged.

**Pull request closed without merging**
