### PR TITLE
put symbol definitions into ROM with gperf

### PR DESCRIPTION
**Pull request by yurie**
This is a patch to put symbol definitions into ROM, as I talked in RubyKaigi 2018.

This patch generates perfect hash function with gperf instead of khash.
With the patch, pre-defined symbols are in ROM area, not in khash struct in RAM, so mruby consume less RAM memory in execution time for embedded environments.

### Usage

Define macro `USE_PRESYM` in build_config.rb.

```ruby
  conf.cc.defines = %w(USE_PRESYM)
```

Without `USE_PRESYM`, nothing changed.

### struct and functions

The patch add a struct and two functions in include/mruby/presym.h.

* `struct name2presym` for name and symbol number pairs.
* `const struct name2presym *presym_find(const char *, unsigned int);` returns name2presym from name and its length.
* `const char *presym_sym2name(uint32_t sym);` returns pointer to symbol name from symbol number.

These functions are defined in src/presym.c, that is generaged by gperf.

### Rake tasks

We add Rake tasks to update src/presym.c.

* `rake presym:build` scan `src/*.c` and `mrblib/*.rb`, and update src/presym.c

`presym:build` execute 3 sub tasks. This task geneartes src/presym.json as imidiate list of symbols.
You can edit presym.json to add other symbols you may use.

* `rake presym:gen_json` find symbols in `src/*.c` and `mrblib/*.rb`, and generate JSON file.
* `rake presym:gen_key` load JSON file and generate presym.key for gperf.
* `rake presym:gen_c` generate presym.c from presym.key with gperf.

(Note: we will make another PR to put method table into ROM.)

### CODE REVIEW

**Comment by matz** [comment]
@yurie @takahashim It is very interesting we have another pull request to address a similar problem.
What do you think about #4076?

**Comment by dearblue** [comment]
Since I can neglect the work of #4076 any more, I would like to be unified into this #4078!
It is better that the khash table is integrated as well.

   - For decrease the amount of RAM
   - For the amount of increase in ROM
   - For speed reduction

I would like a comparison it.

**Comment by matz** [comment]
FYI, `minirake` does not support `namespace`. We need to either remove `namespace` from the `presym` build, or hack `minirake` to support `namespace`.

**Comment by matz** [comment]
Static (ROM-able) symbols are implemented in a different way in `mruby3` branch.

**Pull request closed without merging**
