### PR TITLE
Improve compatibility to CRuby for `Float#to_s`

### PR DESCRIPTION
**Pull request by shuujii**
### Bfore:

  ~~~ruby
  p Float::INFINITY.to_s  #=> "inf"
  p 50.0.to_s             #=> "50"
  p 1e20.to_s             #=> "1e+20"
  ~~~

### After / CRuby:

  ~~~ruby
  p Float::INFINITY.to_s  #=> "Infinity"
  p 50.0.to_s             #=> "50.0"
  p 1e20.to_s             #=> "1.0e+20"
   ~~~

### CODE REVIEW

**Comment by take-cheeze** [comment]
Not a revert request but we should be careful that mruby promotes overflowed integer since mruby doesn't have `BigInt`.
Related issues cause by this PR:
https://github.com/mattn/mruby-json/pull/40
https://github.com/pepabo/mruby-msd/pull/13
https://github.com/mattn/mruby-json/pull/42

**Comment by matz** [comment]
OK, I will revert part of this PR.

**Comment by matz** [comment]
So I removed explicit `.0` addition at the end from `Float#to_s`. @take-cheeze could you check it solves mrbgems problems?

**Comment by take-cheeze** [comment]
LGTM now

**Comment by matz** [comment]
Thank you.

**Comment by shuujii** [comment]
Is it okay in the case of exponential notation? (e.g. `3.0e+45`)

**Comment by matz** [comment]
I think so. The only reason I tried to remove the trailing `.0` is integer compatibility, so exponential notation is not included.

**Pull request merged**
