### PR TITLE
mruby-1.2.0

### PR DESCRIPTION
**Pull request by mimaki**
mruby 1.2.0

### CODE REVIEW

**Comment by zzak** [comment]
Hello! Thanks for your work on mruby.

I'd like to merge #3013 before doing the release.

Any other bug fixes we should know about?

**Comment by cremno** [comment]
#2902 - Two error backtrace bugs. I've linked a commit that fixes one of them. Maybe a rebase and a review is needed. I think I'm going to create a PR.

#2915 - Not the PR itself but I still think `ENABLE_DEBUG` should be renamed (and `ENABLE_STDIO` probably too). I'll create a PR replacing `ENABLE_DEBUG` with `MRB_DEBUG_HOOKS` in a few minutes. Alternative name suggestions until then are welcome.

**Comment by matz** [comment]
#3013 merged. If you have last minute check-in candidates in mind, please tell us.
I will merge this in a week or two.

**Comment by matz** [comment]
@mimaki ah, do you want it before IT expo?
If so, I will try to prepare the release within Tuesday (17th).

**Comment by mimaki** [comment]
@matz yes, I think so.
Best regards.

2015-11-17 2:43 GMT+09:00 matz <notifications@github.com>:

**Pull request closed without merging**
