### PR TITLE
Traditional, UNC, and Drive Path

### PR DESCRIPTION
**Pull request by Reckordp**
added several types of paths for windows only
and some additions :D

### CODE REVIEW

**Comment by shuujii** [comment]
I think that the argument `len` of `mrb_file_is_absolute_path()` is unnecessary because differences in the signature of the function between Windows and others cause confusion.

And the type of `len` should be `size_t`, I think.

**Comment by shuujii** [comment]
Sorry, I didn't realize @matz had already made the same fix as my comment. Thank you.

**Comment by Reckordp** [comment]
Nice

**Comment by Reckordp** [comment]
Nice

**Pull request merged**
