### PR TITLE
Fix ownership error in vformat test

### PR DESCRIPTION
**Pull request by take-cheeze**

### CODE REVIEW

**Comment by matz** [comment]
I don't see the reason to protect the `%C` class only. Does this PR fix any real problem?

**Comment by matz** [comment]
I don't see the reason to protect the `%C` class only. Does this PR fix any real problem?

**Comment by take-cheeze** [comment]
This bothers me when testing with `-DMRB_GC_STRESS`.
And object under `RData`'s memory don't get marked so it's potentially unsafe operation anyway.

**Comment by shuujii** [comment]
This issue seems to be resolved by #4622. Will it not be merged?

**Comment by matz** [comment]
I don't think `%C` (class/module) needs to be saved in `TestVFormat::Native`. `%C` should be handled like `%t`.

**Pull request closed without merging**
