### PR TITLE
Added more YARD docs to mruby.h

### PR DESCRIPTION
**Pull request by Mav7**
Wrote reference documentation for mrb_obj_dup, and mrb_obj_respond_to. I Also fixed a mistake I made on mrb_class_defined.

### CODE REVIEW

**Comment by strcmp** [comment]
@Mav7 should valid YARD documentation not include a type annotation also, like:
`@param [Foo] name desc` ? or is it somehow different in mruby?

**Comment by Mav7** [comment]
@strcmp  I think your right my friend! I'll start fixing the docs to fit this. Maybe you can review my new docs later, and tell me if it looks right.

**Comment by Mav7** [comment]
@strcmp When I write `@param [mrb_state *] mrb The current mruby state.` I get `mrb (mrb_state *) — The current mruby state.` In the generated YARD doc. Does that look right?

**Comment by strcmp** [comment]
yeah that looks correct @Mav7, I think everything within "[]" is free form so it should not matter if you are describing ruby or C code, as long as it makes sense to programmers of either :)

**Comment by Mav7** [comment]
@strcmp  Perfect thanks a lot! This is the power of open source!

**Comment by strcmp** [comment]
happy to help.

**Pull request merged**
