### PR TITLE
Remove `patch_irep()` in `mruby-eval`

### PR DESCRIPTION
**Pull request by dearblue**
- It can now deal with operands in the range of `OP_EXT*`.
- It can now call the same method as the variable name without arguments.

  ```ruby
  def a
    "Safe!"
  end

  a = "Auto!"

  eval "a()" # call method `a`
  ```

----

It also includes changes in `mrbgems/mruby-compiler/core/y.tab.c`, so the difference is inflated by more than six times.
The net is as follows:
```console
% git diff --stat master.. -- :^mrbgems/mruby-compiler/core/y.tab.c
 include/mruby/compile.h               |   4 +-
 mrbgems/mruby-compiler/core/codegen.c | 101 +++++++++-------
 mrbgems/mruby-compiler/core/parse.y   |  15 ++-
 mrbgems/mruby-eval/src/eval.c         | 215 +---------------------------------
 mrbgems/mruby-eval/test/eval.rb       |  21 ++++
 5 files changed, 98 insertions(+), 258 deletions(-)
```

I wish there was a better way to do it.

### CODE REVIEW

**Comment by shuujii** [comment]
> It also includes changes in mrbgems/mruby-compiler/core/y.tab.c, so the difference is inflated by more than six times.
> I wish there was a better way to do it.

For the time being, why not just ignore `#line` directive and `yyrline` in the difference in the following steps?

```console
$ touch .gitattributes
$ echo '/mrbgems/mruby-compiler/core/y.tab.c diff=tabc' >> .gitattributes
$ git config diff.tabc.textconv "ruby --disable-gems -0pe 'gsub(/^\\x23line [^\\n]+?\\n|^[^\\n]+?YYRLINEYYN.+?^}\\x3b\\n/m, %())'"
```

**Comment by dearblue** [comment]
Thanks for the comment.
The difference displayed for the time being will be less, but hmm, it is different from what I thought...
Up until about a week ago, FreeBSD was a 3.5 series binary package of bison, so the difference was huge.
It's not always up-to-date bison available, so in that case I may need someone to help me out...

**Comment by matz** [comment]
Merged with the `y.tab.c` generated by the latest bison.

**Comment by dearblue** [comment]
Thanks @matz. And I am sorry for the lack of words.
In this PR, I was using bison-3.6.2 to convert, so it was possible to merge as is (if there are no other problems).

**Pull request closed without merging**
