### PR TITLE
mirb should take filename and arguments.

### PR DESCRIPTION
**Pull request by mattn**
works as same as irb

```
$ cat test.rb
puts "foo"

$ mirb test.rb hello
mirb - Embeddable Interactive Ruby Shell

foo
 => nil
> p ARGV
["hello"]
 => ["hello"]
```

### CODE REVIEW

**Comment by mattn** [comment]
oops, test failed

**Comment by matz** [comment]
The behavior is different from irb (irb terminates after reading from script file). what is the use-case for this change?

**Comment by zzak** [comment]
Should mirb terminate too?

**Comment by matz** [comment]
I just don't know. I cannot imagine the use case.

**Comment by mattn** [comment]
Ah, sorry. I seemed to have seen a vision.

**Comment by matz** [comment]
may I close this issue, or should we make mirb consistent with irb?

**Comment by mattn** [comment]
I already modified change to make behavior as same as irb.

**Comment by matz** [comment]
the point is whether we have to make it compatible to irb or not. I feel the current irb behavior has no benefit.

**Comment by strcmp** [comment]
I think it is more useful to not terminate at the end. At the moment `irb foo.rb` sounds `Kernel#p` and `ruby foo.rb` on steroids. it doesnt seem useful.

**Comment by sagmor** [comment]
Given the purpose of irb it seems natural to pass a file name to "preload" an IRB session. You could be working on a new script and use that functionality to test things out as you go or to fast-forward a tedious setup (DB connection or setup some constants for example) I've came up with times hacking with some new/unknown API when I had to copy and paste multiple times some initial setup script that could have benefited from such functionality. Keeping the session open could help on those scenarios.

On the other hand I see no benefit of closing it on finish. Just use `ruby filename.rb` instead right?

**Comment by pbosetti** [comment]
I second @sagmor comment: `irb filename.rb` can prove useful in preloading setups, which implies that it should not exit on finish.

**Pull request merged**
