### PR TITLE
mruby-1.2.0

### PR DESCRIPTION
**Pull request by mimaki**
mruby-1.2.0

### CODE REVIEW

**Comment by mimaki** [comment]
Dear, cremno.
Thank you for pointing out.

I made merge request again.

**Comment by matz** [comment]
I checked in the changes.  Now we can officially release 1.2.

**Comment by mattn** [comment]
please `git tag 1.2.0 && git push --tags`

**Comment by matz** [comment]
I understand. But I just wanted it to be double checked by @mimaki before adding a tag.

**Comment by mimaki** [comment]
@matz, I was also checked.
I will create the tag of 1.2.0.

2015-11-17 18:08 GMT+09:00 matz <notifications@github.com>:

**Pull request closed without merging**
