### PR TITLE
Fix for empty lines in squiggly heredocs

### PR DESCRIPTION
**Pull request by SeekingMeaning**
Sorry, I have made a mistake in my previous PR https://github.com/mruby/mruby/pull/5246 and forgot to check for empty lines in squiggly heredocs.

### CODE REVIEW

**Comment by shuujii** [comment]
The following result seems to be different from Ruby.

```ruby
# example.rb
p <<~EOS
\t
 a
EOS
```

```console
$ ruby example.rb
"\t\n a\n"
```

```console
$ mruby example.rb
"\na\n"
```

**Comment by shuujii** [comment]
BTW, in Ruby, if the tab is a hard tab (not `\t`), the result seems to change and I'm not sure if it is intentional or not.

https://wandbox.org/permlink/po9PrAiZKOOkZWnn

**Comment by SeekingMeaning** [comment]
Thank you for bringing this up @shuujii, I shall look into this further

**Comment by SeekingMeaning** [comment]
The following input gives me an unexpected output:

```
<<~EOS
⇥This line is prefixed by a tab character.
··⇥This line is prefixed by two spaces and a tab character.
⇥··This line is prefixed by a tab character and two spaces.
EOS
```

Output:

```
This line is prefixed by a tab character.
This line is prefixed by two spaces and a tab character.
··This line is prefixed by a tab character and two spaces.
```

**Pull request merged**
