### PR TITLE
chop with utf-8. fix #2967

### LINKED ISSUE #2967: String#chop(UTF-8String) removes last byte, not character
#### MRuby(enable `MRB_UTF8_STRING`)

```
% ./bin/mirb
mirb - Embeddable Interactive Ruby Shell

> a = "あいうえお"
 => "あいうえお"
> a.chop
 => "あいうえ\343\201"
```

#### CRuby

```
% irb
irb(main):001:0> a = "あいうえお"
=> "あいうえお"
irb(main):002:0> a.chop
=> "あいうえ"
```

### PR DESCRIPTION
**Pull request by mattn**
fix #2967

### CODE REVIEW

**Comment by syohex** [comment]
Thanks for patch. However `rake test` is failed as below. Is this correct ?

```
% git clone https://github.com/mruby/mruby
% git checkout 81ec5f5dc04a45d869ebf393d818cb8d08e0ffbf # latest version now
% vim include/mrbconf.h 
# Enable `MRB_UTF8_STRING`
% rake
% rake test
...
Fail: String#chop [15.2.10.5.11]
 - Assertion[3] Failed: Expected to be equal
    Expected: "あ"
      Actual: "あ\\"
Fail: String#chop! [15.2.10.5.12]
 - Assertion[2] Failed: Expected to be equal
    Expected: "あいうえ\\"
      Actual: "あいうえ"
 - Assertion[3] Failed: Expected to be equal
    Expected: "あいうえ"
      Actual: "あいう"
```

**Comment by mattn** [comment]
Ah, it's single quote in tests.

**Comment by mattn** [comment]
fixed.

**Comment by syohex** [comment]
Thanks for quick response. I confirmed all tests are passed.

**Pull request merged**
