### PR TITLE
Fix take over file scope variables with `mruby` and `mirb` command

### PR DESCRIPTION
**Pull request by dearblue**
- Add `mrbc_cleanup_local_variables()` function with `MRB_API`
- In `mirb` command, the `_` variable is defined after the `-r` switch

### CODE REVIEW

**Comment by shuujii** [comment]
The following example doesn't seem to work as expected:

#### Files

  ```ruby
  # a.rb
  a = 1
  A = ->{a}
  ```

  ```ruby
  # b.rb
  p A.call
  ```

#### mruby

  ```console
  $ bin/mruby -r ./a.rb b.rb
  main
  ```

#### Ruby

  ```console
  $ ruby -r ./a.rb b.rb
  1
  ```

**Comment by dearblue** [comment]
:crying_cat_face: That's true.

I was worried and tried `mrbc`, and it was the same without applying this patch.

```console
% bin/mrbc a.rb
% bin/mrbc b.rb
% bin/mruby -br a.mrb b.mrb
main
```

It seems that can deal with it using `REnv`, but I may not be able to handle it...

**Comment by matz** [comment]
@dearblue It works as CRuby (`1`) on my box.

**Comment by dearblue** [comment]
On FreeBSD 12.1/amd64, after slightly modifying `mrbgems/mruby-print/mrblib/print.rb` of mruby-head (59464f3), the result is as follows.

```console
% git checkout --detach origin/master
HEAD is now at 59464f35 Merge pull request #4935 from mimaki/delete-duplicated-Array-delete_if
% echo 'a,b,c,d,e,f,g,h,i,j,k,l,m,n=1,2,3,4,5,6,7,8,9,10,11,12,13,14; A=->{[a,b,c,d,e,f,g,h,i,j,k,l,m,n]}' >> mrbgems/mruby-print/mrblib/print.rb
% rake -m clean all
...
% bin/mruby -e 'a=999; b=123; c="ccc"; p A.call'
[999, 123, "ccc", main, main, nil, 999, 123, "ccc", main, main, nil, 999, 123]
```

**Comment by dearblue** [comment]
I fixed the problem pointed out by @shuujii and the problem with mruby binary.

**Comment by dearblue** [comment]
I made a mistake.

**Pull request merged**
