### PR TITLE
Remove `super-linter.report` folder

### PR DESCRIPTION
**Pull request by jbampton**
The `super-linter.report` folder does not seem to be listed anymore on https://github.com/github/super-linter

### CODE REVIEW

**Comment by matz** [comment]
LGTM

**Comment by jbampton** [comment]
I found this issue https://github.com/actions/upload-artifact/issues/232 

Still trying to figure it out

**Comment by jbampton** [comment]
They have a `super-linter.log` file now which you can create and I assume upload as an artifact.

I may try on another pull request.

**Comment by matz** [comment]
@jbampton Are you going to create another pull-request? Can I close this?

**Comment by jbampton** [comment]
@matz you can merge this since I think the folder should be removed.

**Pull request merged**
