### PR TITLE
GC cleanup

### PR DESCRIPTION
**Pull request by furunkel**
This restructures and refactors the GC code. This is part of something bigger, but is useful on its own.
I would have run the GC tests if I'd known how to do that ?

All GC related data is now encapsulated in the `mrb_gc` struct. Related declarations, definitions and macros have been moved to `gc.h` or replaced with something better.
In particular, the ugly `is_dead`, `is_black` etc. macros are no longer public and there are no more
GC related unprefixed structure declarations.

This code makes use of C99 flexible array members. Apparently these are even supported by recent
versions of MSVC. However, if you want to support older versions, we might need to add a hack.

### CODE REVIEW

**Comment by furunkel** [comment]
@matz, any complaints or comments about this ?

**Comment by matz** [comment]
Thank you.,
First, I don't think `mrb_gc` is an appropriate struct name. Maybe `mrb_gc_state`? Ah but we have already used that name.
Second, it conflicts with the latest.  Can you rebase?
Third, I worry a little about performance. But probably it's OK.

**Comment by furunkel** [comment]
@matz, the GC test do fail, **even in master** ? I guess they are not relevant anymore ?
I found `mrb_gc` to be quite natural because literally, `mrb->gc_field` now becomes `mrb->gc.field`
and this struct really represents the garbage collector, but of course I am open to suggestions,
any ideas anyone ?
Switching names with what is now `mrb_gc_state` would probably be confusing ?

As for performance, these are mostly just renamings, anything particular you worry about ?

**Comment by cremno** [comment]
>BTW, anyone using MSVC who can ensure flexible array members are no problem ?

They're not a problem: https://msdn.microsoft.com/en-us/library/b6fae073%28v=vs.140%29.aspx.

**Comment by matz** [comment]
I just worried `mrb->gc.field` requires one more redirection, but it seems to be optimizable (thus ignorable) probably.  Ok, I will merge.  If someone come up with better name for `mrb_gc`, we can update.

**Comment by furunkel** [comment]
Thanks !

**Pull request merged**
