### PR TITLE
Change to UTF-8 string reversing with in place

### PR DESCRIPTION
**Pull request by dearblue**
Reverses UTF-8 strings without allocated heap for working memory.

### CODE REVIEW

**Comment by shuujii** [comment]
Great! Just two comments:

- It seems `mrb_str_modify()` is called twice when `MRB_UTF8_STRING` is defined.
- It may be originally, but `mrb_str_modify()` may not be needed if string length is less than 2.

**Comment by dearblue** [comment]
Thanks @shuujii for review.

Your comment is right, so I will correct.

**Comment by dearblue** [comment]
I was rebase and forced push.
Also, since I was mixing bugs, I fix it together.

Bug:
A single UTF-8 string consisting of 2 or more bytes is destroyed.

**Comment by lopopolo** [comment]
@dearblue UTF-8 is a multi-byte encoding which cannot be reversed bytewise since some characters take more than 1 byte, for example "💪"

On CRuby:

```
[2.6.0] > "💪"
=> "💪"
[2.6.0] > "💪".reverse
=> "💪"
[2.6.0] > "💪".reverse.reverse
=> "💪"
```

On mruby with this patch:

```
> "💪"
 => "\xf0\x9f\x92\xaa"
> "💪".reverse
 => "\xaa\x92\x9f\xf0"
> "💪".reverse.reverse
 => "\xf0\x9f\x92\xaa"
```

**Comment by shuujii** [comment]
I can't reproduce it. Do you define `MRB_UTF8_STRING`?

**Comment by lopopolo** [comment]
@shuujii Oh no I did not. Sorry I've been used to my custom build where I set this flag long ago. Please ignore my above comment.

**Comment by dearblue** [comment]
The original approach is to swap the front and back of the array without changing the order of the parts with in-place array.

It is over 10 years (20 years?) since I saw this method, but I can not remember at all where I saw it.

```
Before reversing array:
  [A1 A2 A3  B1 B2 B3 B4]

Reverse the part A:
  [A3 A2 A1  B1 B2 B3 B4]

Reverse the part B:
  [A3 A2 A1  B4 B3 B2 B1]

Reverse whole array to complete:
  [B1 B2 B3 B4  A1 A2 A3]
```

This patch remembers this and just applies to UTF-8 strings.

I should have mentioned the original approach.

**Comment by dearblue** [comment]
I am forgot reports for benchmark.

For small UTF-8 strings, 1.5 times more time is required.

  - Time of `mruby -e '("abcdefghijklmn"*100000000).reverse!'`

    ```console
    % for rev in f94551a reverse-utf8; \
    do \
      git co --detach $rev; \
      CFLAGS='-O3 -Wall -DMRB_UTF8_STRING' ./minirake -j10 `pwd`/build/host/bin/mruby > /dev/null 2> /dev/null; \
      for i in `seq 3`; \
      do \
        /usr/bin/time ./build/host/bin/mruby -e '("abcdefghijklmn"*100000000).reverse!'; \
      done; \
    done
    Previous HEAD position was 98daa3bb6 Fix the unnecessary `mrb_str_modify()` call
    HEAD is now at f94551ad4 Merge pull request #4518 from shuujii/add-ISO-section-number-to-Kernel-local_variables
           11.73 real        10.84 user         0.88 sys
           11.69 real        10.79 user         0.89 sys
           11.84 real        10.92 user         0.91 sys
    Previous HEAD position was f94551ad4 Merge pull request #4518 from shuujii/add-ISO-section-number-to-Kernel-local_variables
    HEAD is now at 11e09dc5d Fix the unnecessary `mrb_str_modify()` call
           11.69 real        10.85 user         0.83 sys
           11.77 real        10.83 user         0.93 sys
           11.71 real        10.86 user         0.83 sys
    ```

  - Time of `mruby -e '100000.times { ("○✕△□"*1000).reverse! }'`

    ```console
    % for rev in f94551a reverse-utf8; \
    do \
      git co --detach $rev; \
      CFLAGS='-O3 -Wall -DMRB_UTF8_STRING' ./minirake -j10 `pwd`/build/host/bin/mruby > /dev/null 2> /dev/null; \
      for i in `seq 3`; \
      do \
        /usr/bin/time ./build/host/bin/mruby -e '100000.times { ("○✕△□"*1000).reverse! }'; \
      done; \
    done
    Previous HEAD position was 98daa3bb6 Fix the unnecessary `mrb_str_modify()` call
    HEAD is now at f94551ad4 Merge pull request #4518 from shuujii/add-ISO-section-number-to-Kernel-local_variables
            4.80 real         4.77 user         0.02 sys
            4.88 real         4.85 user         0.01 sys
            4.74 real         4.73 user         0.00 sys
    Previous HEAD position was f94551ad4 Merge pull request #4518 from shuujii/add-ISO-section-number-to-Kernel-local_variables
    HEAD is now at 98daa3bb6 Fix the unnecessary `mrb_str_modify()` call
            7.40 real         7.38 user         0.00 sys
            7.44 real         7.41 user         0.01 sys
            7.36 real         7.33 user         0.02 sys
    ```

  - Time of `mruby -e '("○✕△□"*100000000).reverse!'`

    ```console
    % for rev in f94551a reverse-utf8; \
    do \
      git co --detach $rev; \
      CFLAGS='-O3 -Wall -DMRB_UTF8_STRING' ./minirake -j10 `pwd`/build/host/bin/mruby > /dev/null 2> /dev/null; \
      for i in `seq 3`; \
      do \
        /usr/bin/time ./build/host/bin/mruby -e '("○✕△□"*100000000).reverse!'; \
      done; \
    done
    Previous HEAD position was 98daa3bb6 Fix the unnecessary `mrb_str_modify()` call
    HEAD is now at f94551ad4 Merge pull request #4518 from shuujii/add-ISO-section-number-to-Kernel-local_variables
            6.93 real         5.50 user         1.43 sys
            6.96 real         5.45 user         1.51 sys
            6.94 real         5.49 user         1.45 sys
    Previous HEAD position was f94551ad4 Merge pull request #4518 from shuujii/add-ISO-section-number-to-Kernel-local_variables
    HEAD is now at 11e09dc5d Fix the unnecessary `mrb_str_modify()` call
            6.67 real         5.90 user         0.76 sys
            6.71 real         5.91 user         0.79 sys
            6.67 real         5.91 user         0.75 sys
    ```

**Pull request merged**
